### PR TITLE
framedblock fix

### PR DESCRIPTION
**Pull request by ferriarnus**
rewrote models to use composite.
rewrote framed loader to use composite-like system and directly change quads.
Need to go and clean up/ fix some stuff.

Question about the models: I started rewriting all to use composites, but this isn't really needed. All I needed was a composite model for the framed block. If you want I can leave the other drawers the way they are now.

### CODE REVIEW

**Comment by ferriarnus** [comment]
Might look into the rotations of the models, but everything else works.

**Comment by Buuz135** [comment]
It looks like one of the more recent commits made it use the full u-v for faces that are not 16 pixel big
NVIDIA_Share_BmGSRwYCEW

**Comment by ferriarnus** [comment]
Oh I'll look. Maybe uvlock cause this? I'll dig some more.

**Review by Buuz135 — APPROVED** [review]

**Comment by Buuz135** [comment]
Fixes #106 in 1.19

**Pull request merged**
